<?=$actualite?>

<div id="boutonReserver">
	<a href="?action=carte" title="reserver maintenant">Réservation<br/>en ligne</a>
</div>

<div class="borderDown"></div>

<div class="widget">
	<div id="TA_cdsratingsonlynarrow778" class="TA_cdsratingsonlynarrow">
	<ul id="MjIRTcaP" class="TA_links w6Fhwdowu">
	<li id="Ga4X9II" class="FtnAO8Km">
	<a target="_blank" href="http://www.tripadvisor.fr/"><img src="http://www.tripadvisor.fr/img/cdsi/img2/branding/tripadvisor_logo_transp_340x80-18034-2.png" alt="TripAdvisor"/></a>
	</li>
	</ul>
</div>
<script src="http://www.jscache.com/wejs?wtype=cdsratingsonlynarrow&amp;uniq=778&amp;locationId=6675003&amp;lang=fr&amp;border=true&amp;display_version=2"></script>
</div>

<div class="borderDown"></div>

<div class="widget">
<div id="fileContent"><a href="http://www.petitfute.com" target="_blank" title="Petit Futé"><img src="http://www.petitfute.com/img/widget/logo.jpg"  width="100" alt="Petit Futé" /></a></div>
<script type="text/javascript" src="http://pro.petitfute.com/compte/widget/petitfute/67356/"></script>
</div>

<div class="borderDown"></div>

<div class="widget">
	<a href="https://www.facebook.com/restaurantletimsam" title="Timsam" target="_TOP"><img class="img" src="https://badge.facebook.com/badge/279176515569382.428.698891451.png" style="border: 0px;" alt="" ></a><br>
</div>

<div class="borderDown"></div>

<div class="widget">
	<iframe id="widgetMiniMap" width="150" height="190" src="https://maps.google.fr/maps?f=q&amp;source=s_q&amp;hl=fr&amp;geocode=&amp;q=78+Rue+du+Vaugueux,+14000+Caen&amp;aq=&amp;sll=49.187906,-0.360004&amp;sspn=0.000285,0.000817&amp;t=m&amp;ie=UTF8&amp;hq=&amp;hnear=78+Rue+du+Vaugueux,+14000+Caen,+Calvados,+Basse-Normandie&amp;ll=49.187482,-0.359974&amp;spn=0.01122,0.014849&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe><br><small><a href="https://maps.google.fr/maps?f=q&amp;source=embed&amp;hl=fr&amp;geocode=&amp;q=78+Rue+du+Vaugueux,+14000+Caen&amp;aq=&amp;sll=49.187906,-0.360004&amp;sspn=0.000285,0.000817&amp;t=m&amp;ie=UTF8&amp;hq=&amp;hnear=78+Rue+du+Vaugueux,+14000+Caen,+Calvados,+Basse-Normandie&amp;ll=49.187482,-0.359974&amp;spn=0.01122,0.014849&amp;z=14&amp;iwloc=A" style="color:#0000FF;text-align:left">Agrandir le plan</a></small>
</div>