<p class="pNormal">Tous droits réservés images et contenus. Développé et maintenu par Pierre Labadille. Propriété exclusive de Som Phouthavy.</p>

<div id="sociaux">
	<a href="https://www.facebook.com/restaurantletimsam" target="_blank"><img class="footerSocial" src="./img/logo_reseau/fb.png" alt="Facebook"></a>
	<a href="https://twitter.com/Timsam_caen" target="_blank"><img class="footerSocial" src="./img/logo_reseau/twitter.png" alt="Twitter"></a>
	<a href="https://plus.google.com/109702457777635317880/posts" target="_blank"><img class="footerSocial" src="./img/logo_reseau/gplus.png" alt="Google+"></a>
	<a href="http://www.tripadvisor.fr/Restaurant_Review-g187182-d6675003-Reviews-Tim_Sam-Caen_Calvados_Basse_Normandie_Normandy.html" target="_blank"><img class="footerSocial" src="./img/logo_reseau/tripad.png" alt="TripAdvisor"></a>
</div>