<footer id="c-base__footer">
    <div id="c-footer__socials">
    	<a class="c-footer__socials-link" href="https://www.facebook.com/restaurantletimsam" target="_blank">
            <img class="c-footer__socials-img" src="./img/logo_reseau/fb.png" alt="Facebook">
        </a>
    	<a class="c-footer__socials-link" href="https://twitter.com/Timsam_caen" target="_blank">
            <img class="c-footer__socials-img" src="./img/logo_reseau/twitter.png" alt="Twitter">
        </a>
    	<a class="c-footer__socials-link" href="https://plus.google.com/109702457777635317880/posts" target="_blank">
            <img class="c-footer__socials-img" src="./img/logo_reseau/gplus.png" alt="Google+">
        </a>
    	<a class="c-footer__socials-link" href="http://www.tripadvisor.fr/Restaurant_Review-g187182-d6675003-Reviews-Tim_Sam-Caen_Calvados_Basse_Normandie_Normandy.html" target="_blank">
            <img class="c-footer__socials-img" src="./img/logo_reseau/tripad.png" alt="TripAdvisor">
        </a>
    </div>

    <div id="c-footer__legal">
        <p class="c-footer__legal-text">
            ©Timsam 2017 - V3.0
            </br>
            Développé et maintenu par Pierre Labadille.
        </p>
    </div>

    <div id="sitelock_shield_logo" class="fixed_btm" style="bottom:0;position:fixed;_position:absolute;right:0;"><a href="https://www.sitelock.com/verify.php?site=le-timsam.com" onclick="window.open('https://www.sitelock.com/verify.php?site=le-timsam.com','SiteLock','width=600,height=600,left=160,top=170');return false;" ><img alt="PCI Compliance and Malware Removal" title="SiteLock" src="//shield.sitelock.com/shield/le-timsam.com"></a></div>
</footer>
