<p class="pNormal">Tous droits réservés images et contenus. Développé et maintenu par Pierre Labadille. Propriété exclusive de Som Phouthavy. </br>©Timsam 2016 - V2.0 - Optimisé pour Mozilla Firefox</p>

<div id="sociaux">
	<a href="https://www.facebook.com/restaurantletimsam" target="_blank"><img class="footerSocial" src="./img/logo_reseau/fb.png" alt="Facebook"></a>
	<a href="https://twitter.com/Timsam_caen" target="_blank"><img class="footerSocial" src="./img/logo_reseau/twitter.png" alt="Twitter"></a>
	<a href="https://plus.google.com/109702457777635317880/posts" target="_blank"><img class="footerSocial" src="./img/logo_reseau/gplus.png" alt="Google+"></a>
	<a href="http://www.tripadvisor.fr/Restaurant_Review-g187182-d6675003-Reviews-Tim_Sam-Caen_Calvados_Basse_Normandie_Normandy.html" target="_blank"><img class="footerSocial" src="./img/logo_reseau/tripad.png" alt="TripAdvisor"></a>
</div>
<div id="sitelock_shield_logo" class="fixed_btm" style="bottom:0;position:fixed;_position:absolute;right:0;"><a href=			"https://www.sitelock.com/verify.php?site=le-timsam.com" onclick="window.open('https://www.sitelock.com/verify.php?site=le-timsam.com','SiteLock','width=600,height=600,left=160,top=170');return false;" ><img alt="PCI Compliance and Malware Removal" title="SiteLock" src="//shield.sitelock.com/shield/le-timsam.com"></a></div>
