<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="utf-8">
	<title><?=$title?></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<META NAME="KEYWORDS" CONTENT="restaurant, restaurant asiatique, restaurant vietnamiens, restaurant laotiens, salon de thé, restaurant thaïlandais,">
	<META NAME="description" content="Le Timsam est un restaurant de spécialités du Sud-Est asiatique proposant des plats issus de recettes traditionnelles faits maison à base de produits frais. Le restaurant vous proposes des spécialités laosiennes, vietnamiennes, thaïlandaises... Le restaurant est ouvert du mardi au samedi et propose de nombreux événéments culturels : expositions, dîner-concerts." />
	<link rel="icon" type="image/jpg" href="img/accueil/timsamFaviconl.jpg" />
	<link rel="stylesheet" href="css/normalize.css">
	<!-- Lightbox css -->
	<link rel="stylesheet" type="text/css" href="js/lightbox-2.7.1/css/lightbox.css" >
	<link rel="stylesheet" href="css/style.css">
</head>
