<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="utf-8">
	<title><?=$title?></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="keywords" content="restaurant, restaurant asiatique, restaurant vietnamiens, restaurant laotiens, salon de thé, restaurant thaïlandais,">
	<meta name="description" content="Le Timsam est un restaurant de spécialités du Sud-Est asiatique proposant des plats issus de recettes traditionnelles faits maison à base de produits frais. Le restaurant vous proposes des spécialités laosiennes, vietnamiennes, thaïlandaises... Le restaurant est ouvert du mardi au samedi et propose de nombreux événéments culturels : expositions, dîner-concerts." />
	<link rel="icon" type="image/jpg" href="/img/accueil/timsamFaviconl.jpg" />

	<!-- Dublin Core -->
    <meta name="DC.Title" content="Restaurant le Timsam" />
    <meta name="DC.Creator" content="Pierre Labadille" />
    <meta name="DC.Publisher" content="Pierre Labadille" />
    <meta name="DC.Contributor" content="Som Phouthavy" />

	<!-- Global data Graph -->
	<meta property="og:site_name" content="Restaurant le Timsam" />
    <meta property="og:locale" content="fr_FR" />

	<!-- Data Graph for articles -->
	<?php if (isset($meta_facebook) && isset($og_url)) { ?>
	<meta property="og:url" content="<?=$og_url?>" />
	<meta property="og:type" content="article" />
	<meta property="og:title" content="<?=$og_title?>" />
	<meta property="og:description" content="<?=$og_description?>" />
	<meta property="og:image" content="<?=$og_image?>" />
	<?php } ?>

	
	<!-- Vendor CSS -->
	<link rel="stylesheet" href="/css/vendor/normalize.css">
	<link rel="stylesheet" type="text/css" href="/js/lightbox-2.7.1/css/lightbox.css" >

	<!-- CSS -->
	<link rel="stylesheet" href="/css/default.css">
	<link rel="stylesheet" href="/css/base.css">
	<link rel="stylesheet" href="/css/header.css">
	<link rel="stylesheet" href="/css/main.css">
	<link rel="stylesheet" href="/css/service.css">
	<link rel="stylesheet" href="/css/avis.css">
	<link rel="stylesheet" href="/css/evenement.css">
	<link rel="stylesheet" href="/css/article.css">
	<link rel="stylesheet" href="/css/carte.css">
	<link rel="stylesheet" href="/css/nav.css">
	<link rel="stylesheet" href="/css/footer.css">

</head>
