<ul id="navigationMobile">
	<li><a href="">Menu  </a>
	</li>
</ul>
<ul id="navigation">
		<li><a href="index.php">Accueil</a></li>
		<li><a href="?action=services">Services</a>
			<ul>
				<li><a href="?action=services">Nos services</a></li>
				<li><a href="?action=restaurant">Restaurant</a></li>
				<li><a href="?action=cartecadeau">Carte cadeau</a></li>
			</ul>
		</li>
		<li><a href="?action=carte">Produits</a>
			<ul>
				<li><a href="?action=carte">La carte</a></li>
				<li><a href="?action=entrees">Nos entrées</a></li>
				<li><a href="?action=plats">Nos plats</a></li>
				<li><a href="?action=desserts">Nos desserts</a></li>
			</ul>
		</li>
		<li><a href="?action=event">Animations</a>
			<ul>
				<li><a href="?action=event">Evénements</a></li>
				<li><a href="?action=galerie">Galerie</a></li>
				<li><a href="?action=agenda">Agenda</a></li>
			</ul>
		</li>
		<li><a href="?action=contact">Contact</a></li>
</ul>

