<nav id="c-base__nav">
    <ul id="c-nav__main-items">
        <li class="c-nav__main-item">
            <a class="c-nav__main-link" href="./index.php">
                <i class="c-nav__main-icon icon-home"></i>
                Accueil           
            </a>
        </li>
        
    	<li class="c-nav__main-item">
            <a class="c-nav__main-link" href="./service.php">
                <i class="c-nav__main-icon icon-service"></i>
                Services
            </a>
        </li>

        
    	<li class="c-nav__main-item">
            <a class="c-nav__main-link" href="./avis.php">
                <i class="c-nav__main-icon icon-review"></i>
                Avis
            </a>
        </li>
        
    	<li class="c-nav__main-item">
            <a class="c-nav__main-link" href="./evenement.php">
                <i class="c-nav__main-icon icon-event"></i>
                Animations
            </a>
        </li>
        
        <li class="c-nav__main-item">
            <a class="c-nav__main-link" href="./reservation.php">
                <i class="c-nav__main-icon icon-booking"></i>
                Réservation
            </a>
        </li>

    </ul>
</nav>