<?php include 'templates/head.phtml' ?>
<body>
	<header>
		<?php include 'templates/header.phtml' ?>
	</header>
	<div id="container">
		<main>
			<section id="contentMain" role="corp de la page">
				<?=$main?>
			</section>
			<aside id="comAside">
				<?php include 'view/templates/aside.phtml' ?>
			</aside>
		</main>
		<nav id="mainNav">
			<?=$nav?>
		</nav>
	</div>
	<footer>
		<?php include 'view/templates/footer.phtml' ?>
	</footer>
	
	<script type="text/javascript" src="js/script.js"></script>

</body>
</html>